# Site
name: "Learnfie"
title: "Learnfie"
description: "Learn with passion"
logo: 'assets/images/learnfie.png'
favicon: 'favicon.ico'
baseurl: ''
google_analytics: 'UA-74891597-1'
disqus: 'learnfie'
mailchimp-list: 'https://learnfie.us7.list-manage.com/subscribe?u=4bbf1fa421bf81678fa3b140b&id=ee7b4b2d9b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  arman:
    name: Arman
    display_name: Arman
    gravatar: 81e0446b764cdb187af6cf6cefe6898d
    email: armans.postbox@gmail.com
    web: https://arman-bd.github.io
    twitter: https://twitter.com/armanfie
    description: "Author of Learnfie, currently working as Mobile Application Developer at Shakti Foundation."
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
